# Introduction to Scikit learn

In [8]:
# Get the data ready
import pandas as pd
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [9]:
# create x features
X = heart_disease.drop("target", axis=1)

In [10]:
#create y label
y = heart_disease["target"]

In [11]:
#2 choose the right model & hyperparameter
from sklearn.ensemble import RandomForestClassifier
clf= RandomForestClassifier()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [12]:
#3 fit the model to the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
clf.fit(X_train, y_train);

In [13]:
#make a prediction
import numpy as np
y_label = clf.predict(np.array([0,1,2,3,4]))

ValueError: Expected 2D array, got 1D array instead:
array=[0. 1. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [14]:
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
15,50,0,2,120,219,0,1,158,0,1.6,1,0,2
10,54,1,0,140,239,0,1,160,0,1.2,2,0,2
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
78,52,1,1,128,205,1,1,184,0,0.0,2,0,2
112,64,0,2,140,313,0,1,133,0,0.2,2,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2
69,62,0,0,124,209,0,1,163,0,0.0,2,0,2
283,40,1,0,152,223,0,1,181,0,0.0,2,0,3
224,54,1,0,110,239,0,1,126,1,2.8,1,1,3
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2

In [15]:
y_preds = clf.predict(X_test)

In [16]:
y_preds

array([1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [17]:
y_test

15     1
10     1
301    0
78     1
112    1
      ..
302    0
69     1
283    0
224    0
2      1
Name: target, Length: 61, dtype: int64

In [18]:
#Evaluate the model
clf.score(X_train, y_train)

1.0

In [19]:
clf.score(X_test,y_test)

0.7704918032786885